import './globals.css'
import Link from 'next/link'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='navbar'>
          <Link href="/">홈</Link>
          <Link href="/list">게시판</Link>
          <Link href="/write">글작성</Link>
        </div>
        <main>{children}</main>
      </body>
    </html>
  )
}
